[package]
name = "c2rust-init"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[dependencies]
clap = { version = "4", features = ["derive"] }
git2 = "0.19"

[dev-dependencies]
tempfile = "3"
